name: acr-1
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-acr
      - manual-trigger-acr-1
  schedule:
    - cron: '0 6 * * *'
permissions:
      id-token: write
      contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: https://ociconformancetest.azurecr.io
          OCI_NAMESPACE: ocitest/pull
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          OCI_TEST_PULL: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: 'Az CLI login'
        if: always()
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Publish test results'
        if: always()
        run: |
            az storage blob upload --account-name ociconformance --container-name test-results --name pull/report.html --file ./report.html --auth-mode login
            az storage blob upload --account-name ociconformance --container-name test-results --name pull/junit.html --file ./junit.xml --auth-mode login
